In [0]:
import numpy as np

In [23]:
A = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print(A)

[[1 2 3]
 [2 5 6]
 [6 7 4]]
1


In [15]:

b = np.array([1,2, 3])
C = A[:,0] - b
print(C)
A[1,:].min()

[0 0 3]


2

In [22]:
row = np.array([0,0,0])
for i in range(3):
  row[i] = A[i,:].min()
print(row )  


[1 2 4]


1

In [26]:
for i in range(3):
  for j in range(3):
    A[i, j]=A[i, j] - row[i]
  
print(A)  

[[0 1 2]
 [0 3 4]
 [2 3 0]]


In [28]:
column = np.array([0,0,0])
for i in range(3):
  column[i] = A[:,i].min()
print(column)

[0 1 0]


In [30]:
for j in range(3):
  for i in range(3):
    A[i, j]=A[i, j] - column[j]
  
print(A) 

[[0 0 2]
 [0 2 4]
 [2 2 0]]
